// Package apiv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package apiv2

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for JobState.
const (
	Finished JobState = "finished"
	Pending  JobState = "pending"
	Running  JobState = "running"
)

// Defines values for Role.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Defines values for ValueType.
const (
	Integer ValueType = "integer"
	Real    ValueType = "real"
	String  ValueType = "string"
)

// Defines values for Visibility.
const (
	Private Visibility = "private"
	Public  Visibility = "public"
)

// Blueprint defines model for Blueprint.
type Blueprint struct {
	ArchiveID  string     `json:"archiveID"`
	CreatedAt  time.Time  `json:"createdAt"`
	Desc       *string    `json:"desc,omitempty"`
	Id         string     `json:"id"`
	In         []Field    `json:"in"`
	Name       string     `json:"name"`
	Out        []Field    `json:"out"`
	OwnerID    string     `json:"ownerID"`
	Visibility Visibility `json:"visibility"`
}

// CreateBlueprintRequest defines model for CreateBlueprintRequest.
type CreateBlueprintRequest struct {
	ArchiveID string  `json:"archiveID"`
	Desc      *string `json:"desc,omitempty"`
	In        []Field `json:"in"`
	Name      string  `json:"name"`
	Out       []Field `json:"out"`
}

// CreateBlueprintResponse defines model for CreateBlueprintResponse.
type CreateBlueprintResponse struct {
	BlueprintID string `json:"blueprintID"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
	Role     Role   `json:"role"`
}

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	UserID string `json:"userID"`
}

// Field defines model for Field.
type Field struct {
	Desc *string   `json:"desc,omitempty"`
	Name string    `json:"name"`
	Type ValueType `json:"type"`
	Unit *string   `json:"unit,omitempty"`
}

// GetBlueprintResponse defines model for GetBlueprintResponse.
type GetBlueprintResponse = Blueprint

// GetBlueprintsResponse defines model for GetBlueprintsResponse.
type GetBlueprintsResponse = []Blueprint

// GetJobsResponse defines model for GetJobsResponse.
type GetJobsResponse = []Job

// GetUserMeResponse defines model for GetUserMeResponse.
type GetUserMeResponse = User

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse = User

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse = []User

// InvalidInputError defines model for InvalidInputError.
type InvalidInputError struct {
	// Code Уникальный код ошибки.
	Code string `json:"code"`

	// Message Сообщение об ошибке.
	Message *string `json:"message,omitempty"`
}

// Job defines model for Job.
type Job struct {
	ArchiveID   string     `json:"archiveID"`
	BlueprintID string     `json:"blueprintID"`
	CreatedAt   time.Time  `json:"createdAt"`
	FinishedAt  *time.Time `json:"finishedAt,omitempty"`
	Id          string     `json:"id"`
	Input       []Value    `json:"input"`
	Out         []Field    `json:"out"`
	OwnerID     string     `json:"ownerID"`
	Result      *JobResult `json:"result,omitempty"`
	StartedAt   *time.Time `json:"startedAt,omitempty"`
	State       JobState   `json:"state"`
}

// JobResult defines model for JobResult.
type JobResult struct {
	Code    int     `json:"code"`
	Message *string `json:"message,omitempty"`
	Output  []Value `json:"output"`
}

// JobState defines model for JobState.
type JobState string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"accessToken"`
}

// PatchUserRequest defines model for PatchUserRequest.
type PatchUserRequest struct {
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
	Role     *string `json:"role,omitempty"`
}

// PatchUserResponse defines model for PatchUserResponse.
type PatchUserResponse = User

// PlainError defines model for PlainError.
type PlainError struct {
	// Message Сообщение об ошибке.
	Message string `json:"message"`
}

// Role defines model for Role.
type Role string

// SearchBlueprintsResponse defines model for SearchBlueprintsResponse.
type SearchBlueprintsResponse = []Blueprint

// StartJobRequest defines model for StartJobRequest.
type StartJobRequest struct {
	Values []Value `json:"values"`
}

// StartJobResponse defines model for StartJobResponse.
type StartJobResponse struct {
	JobID string `json:"jobID"`
}

// UploadFileResponse defines model for UploadFileResponse.
type UploadFileResponse struct {
	FileID string  `json:"fileID"`
	Size   float32 `json:"size"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Email     string    `json:"email"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	Role      Role      `json:"role"`
}

// Value defines model for Value.
type Value struct {
	Type  ValueType `json:"type"`
	Value *string   `json:"value,omitempty"`
}

// ValueType defines model for ValueType.
type ValueType string

// Visibility defines model for Visibility.
type Visibility string

// SearchBlueprintsParams defines parameters for SearchBlueprints.
type SearchBlueprintsParams struct {
	// Name Название или часть названия шаблона (blueprint).
	Name string `form:"name" json:"name"`
}

// UploadFileMultipartBody defines parameters for UploadFile.
type UploadFileMultipartBody struct {
	// Attachment Файл для загрузки на сервер.
	Attachment openapi_types.File `json:"attachment"`
}

// GetJobsParams defines parameters for GetJobs.
type GetJobsParams struct {
	State *JobState `form:"state,omitempty" json:"state,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateBlueprintJSONRequestBody defines body for CreateBlueprint for application/json ContentType.
type CreateBlueprintJSONRequestBody = CreateBlueprintRequest

// StartJobJSONRequestBody defines body for StartJob for application/json ContentType.
type StartJobJSONRequestBody = StartJobRequest

// UploadFileMultipartRequestBody defines body for UploadFile for multipart/form-data ContentType.
type UploadFileMultipartRequestBody UploadFileMultipartBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// PatchUserJSONRequestBody defines body for PatchUser for application/json ContentType.
type PatchUserJSONRequestBody = PatchUserRequest
