DROP TYPE IF EXISTS VISIBILITY CASCADE;

DROP TYPE IF EXISTS FIELD_TYPE CASCADE;

DROP TYPE IF EXISTS PARAM_TYPE CASCADE;

DROP TABLE IF EXISTS fields CASCADE;

DROP TABLE IF EXISTS scripts CASCADE;

DROP TABLE IF EXISTS script_fields CASCADE;

DROP TABLE IF EXISTS parameters CASCADE;

DROP TABLE IF EXISTS jobs CASCADE;

DROP TABLE IF EXISTS job_params CASCADE;
