DO $$ BEGIN
    CREATE TYPE VISIBILITY AS ENUM ('public', 'private');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE FIELD_TYPE AS ENUM ('integer', 'real', 'complex');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE PARAM_TYPE AS ENUM ('in', 'out');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    CREATE TYPE JOB_STATE AS ENUM ('pending', 'running', 'finished');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


CREATE TABLE fields (
    field_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (LENGTH(name) <= 80),
    description TEXT NOT NULL CHECK (LENGTH(description) <= 512),
    unit TEXT NOT NULL CHECK (LENGTH(unit) <= 40),
    field_type FIELD_TYPE NOT NULL,
    param PARAM_TYPE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE files (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL UNIQUE CHECK (LENGTH(url) <= 300),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scripts (
    script_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (LENGTH(name) <= 160),        
    description TEXT CHECK (LENGTH(description) <= 640),   
    visibility VISIBILITY NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    main_file_id BIGINT NOT NULL,
    FOREIGN KEY (main_file_id) REFERENCES files(file_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE script_files (
    script_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    PRIMARY KEY (script_id, file_id),
    FOREIGN KEY (script_id) REFERENCES scripts(script_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(file_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE script_fields (
    script_id BIGINT NOT NULL,
    field_id BIGINT NOT NULL,
    PRIMARY KEY (script_id, field_id),
    FOREIGN KEY (script_id) REFERENCES scripts(script_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (field_id) REFERENCES fields(field_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE parameters (
    parameter_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    field_id BIGINT NOT NULL,
    value TEXT NOT NULL CHECK (LENGTH(value) <= 100),
    FOREIGN KEY (field_id) REFERENCES fields(field_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE jobs (
    job_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_code INT,
    state JOB_STATE NOT NULL DEFAULT 'pending',
    error_message TEXT,
    script_id BIGINT NOT NULL,
    FOREIGN KEY (script_id) REFERENCES scripts(script_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE job_params (
    job_id BIGINT NOT NULL,
    parameter_id BIGINT NOT NULL,
    PRIMARY KEY (job_id, parameter_id),
    FOREIGN KEY (job_id) REFERENCES jobs(job_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (parameter_id) REFERENCES parameters(parameter_id) ON DELETE CASCADE ON UPDATE CASCADE
);
