openapi: 3.0.4
servers:
- url: "{url}/api"
  variables:
    url:
      default: localhost:8080

info:
  title: Scriptum - OpenAPI 3.0
  version: 1.0.2

tags:
- name: scripts
  description: Scripts
- name: jobs
  description: Jobs (~= pipelines)

paths:
  /scripts:
    get:
      tags:
      - scripts
      summary: Get scripts
      description: Get public scripts and maybe user scripts if user is not admin.
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Script'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
      - scripts
      summary: Create new script
      description: Create new script
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScriptCreateData'
      responses:
        '201':
          description: created new script
          content:
            application/json:
              schema:
                type: object
                properties:
                  script_id:
                    type: integer
                    format: int64
                  message:
                    type: string
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scripts/{id}:
    get:
      tags:
      - scripts
      summary: Get script by script id
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/ScriptId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Script'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: forbidden (script doesn't belong to user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: script not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
      - scripts
      summary: Delete script
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/ScriptId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: forbidden (delete script but for another user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: script not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scripts/{id}/start:
    post:
      tags:
      - scripts
      summary: Run script
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/ScriptId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScriptRunData'
      responses:
        '202':
          description: request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: forbidden (run script but for another user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: script not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scripts/search:
    get:
      tags:
      - scripts
      summary: Search scripts
      description: Search scripts by user id and substring of script name
      parameters:
      - in: query
        name: script_name
        description: substring of script name
        schema:
          type: string
          example: "Подсчёт"
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Script'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /scripts/upload:
    post:
      tags:
      - scripts
      summary: Upload script
      description: Upload file of script
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
              - file
      responses:
        '201':
          description: file uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_id:
                    type: integer
                    format: int64
                  message:
                    type: string
                    example: "File uploaded successfully"
                required:
                - file_id
                - message
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /jobs:
    get:
      tags:
      - jobs
      summary: Get user jobs
      description: Get user jobs' results
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /jobs/search:
    get:
      tags:
      - jobs
      summary: Search jobs
      description: Search for jobs by user id and script name
      parameters:
      - in: query
        name: state
        description: job state
        schema:
          $ref: '#/components/schemas/Status'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Result'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /jobs/{id}/result:
    get:
      tags:
      - jobs
      summary: Get job result
      description: Get the result of a job
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/JobId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
          headers:
            Content-Disposition:
              schema:
                type: string
              example: "attachment; filename=job_result_export.json"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: forbidden (get but for another user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /jobs/{id}/result/download:
    get:
      tags:
      - jobs
      summary: Get job result
      description: Get the result of a job
      parameters:
      - in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/JobId'
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              schema:
                type: string
              example: "attachment; filename=job_result_export.csv"
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: forbidden (get but for another user)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    UserId:
      type: integer
      format: int64
      example: 1
    ScriptId:
      type: integer
      format: int64
      example: 1
    JobId:
      type: integer
      format: int64
      example: 1
    Field:
      type: object
      properties:
        type:
          type: string
          example: "real"
        name:
          type: string
          example: "Длина полёта пули"
        description:
          type: string
          example: "длина полета пули в ветренную погоду против ветра"
        unit:
          type: string
          example: "метры"
      required:
      - type
      - name
      - description
      - unit
    FilePath:
      type: string
      example: "/user1/script7/main.py"
    Visibility:
      type: string
      enum: [ public, private ]
      default: private
    Script:
      type: object
      properties:
        script_id:
          $ref: '#/components/schemas/ScriptId'
        script_name:
          type: string
          example: "Подсчет скорости полета пули в ветренную погоду"
        script_description:
          type: string
          example: "Скрипт для подсчета скорости полета пули в ветренную погоду"
        in_fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        out_fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        file_id:
          type: integer
          format: int64
        owner:
          $ref: '#/components/schemas/UserId'
        visibility:
          $ref: '#/components/schemas/Visibility'
        created_at:
          type: string
          format: date-time
      required:
      - script_id
      - script_name
      - script_description
      - in_fields
      - out_fields
      - file_id
      - owner
      - visibility
      - created_at
    Value:
      type: object
      properties:
        type:
          type: string
          example: "complex"
        data:
          type: string
          example: "-1.6+24.04j"
      required:
      - type
      - data
    Status:
      type: string
      enum: [ pending, running, finished ]
      default: pending
    Job:
      type: object
      properties:
        job_id:
          $ref: '#/components/schemas/JobId'
        user_id:
          $ref: '#/components/schemas/UserId'
        script_id:
          $ref: '#/components/schemas/ScriptId'
        script_name:
          type: string
          example: "Скорость пули"
        in:
          type: array
          items:
            $ref: '#/components/schemas/Value'
        expected:
          type: array
          items:
            $ref: "#/components/schemas/Field"
        path:
          $ref: "#/components/schemas/FilePath"
        status:
          $ref: "#/components/schemas/Status"
        created_at:
          type: string
          format: date-time
        need_to_notify:
          type: boolean
          default: false
        finished_at:
          type: string
          format: date-time
      required:
      - job_id
      - user_id
      - script_id
      - script_name
      - in
      - expected
      - path
      - status
      - created_at
      - need_to_notify
    Result:
      type: object
      properties:
        job:
          $ref: '#/components/schemas/Job'
        code:
          type: integer
        out:
          type: array
          items:
            $ref: '#/components/schemas/Value'
        error_message:
          type: string
          example: "bruh"
      required:
      - job
    Error:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    ScriptCreateData:
      type: object
      properties:
        script_name:
          type: string
          example: "Подсчет скорости полета пули в ветренную погоду"
        script_description:
          type: string
          example: "Скрипт для подсчета скорости полета пули в ветренную погоду"
        in_fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        out_fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        file_id:
          type: integer
          format: int64
      required:
      - script_name
      - script_description
      - in_fields
      - out_fields
      - file_id
    ScriptRunData:
      type: object
      properties:
        in_params:
          type: array
          items:
            $ref: '#/components/schemas/Value'
        need_to_notify:
          type: boolean
          default: false
      required:
      - in_params

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
- BearerAuth: []
